lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: My Blog
description: 我的博客分为项目演示和开发笔记两部分。
show_downloads: true
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme